[package]
name = "auto-fuzz-test"
version = "0.1.0"
authors = ["Eh2406 <YeomanYaacov@gmail.com>", "Sergey \"Shnatsel\" Davidoff <shnatsel@gmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0.8"
syn = {version="1.0.58", features = ["full", "visit"] }
toml = "0.5"
